### ISSUE TITLE
Tree view to be resized automatically or manually in the browser

### ISSUE THREAD

**Issue by myksto71** [lrsjng/h5ai#822] opened 2021-12-02 08:53 UTC
It would be very good if the tree view folder list could be resized automatically in the browser. In cases where the number of subfolders is medium or high their names become invisible or hidden unser the bar. Is there a simple way to achieve it with the code?
Here's a picture of what I mean: 
![Directory_Tree](https://user-images.githubusercontent.com/39297775/144388923-4805200a-03d9-4b5e-a22a-51f4d63cef93.jpg)

I hope you'll find a solution for this wonderful project.

Thanks a lot,

cheers,

Michele.

**Comment by glubsy** [comment] 2021-12-02 15:27
Duplicate of #503. 

It's probably easy to fix, at the very least to enable the horizontal scroll bar.

**Comment by myksto71** [comment] 2021-12-03 08:31
Ok, glad to know it's probably easy to fix.
Is there something I can do to fix it by myself? Some lines of code?
Thanks for your reply.

**Comment by glubsy** [comment] 2021-12-03 15:15
I don't have time to work on this right now, but I suspect you could achieve that through CSS ([example](https://www.geeksforgeeks.org/make-a-div-horizontally-scrollable-using-css/)). 

I have added this to my personal TODO list, but I can't tell when I'll get around to work on it.

**Comment by myksto71** [comment] 2021-12-03 16:00
I really thank you for your time and for you advice.
To tell the truth I'm not familiar with CSS, nor HTML, nor JS. I'm a system engineer who manage windows and linux systems. I can install and configure webservers like Apache but really I wouldn't know which files to modify and write the code you linked me. If you would be so kind to tell me which file I should write the code in it would be great.
Anyway I just thank you for your answer and wait for you to work on it as soon as you can.

Cheers,
Michele.

**Comment by glubsy** [comment] 2021-12-03 17:14
edit the file [src/_h5ai/public/css/lib/ext/tree.less](https://github.com/lrsjng/h5ai/blob/aa94de4945e69ff742525cd4d648c91e5c9d8cd2/src/_h5ai/public/css/lib/ext/tree.less#L9) and look at the beginning of the file for:

```CSS
overflow-x: hidden;
``` 

and change it to:
```CSS
overflow-x: auto;
```

You'll have to recompile the files, and it should work.

**Comment by glubsy** [comment] 2021-12-03 20:24
If you don't want to bother recompiling, just edit your (already deployed) `_h5ai/public/css/styles.css` file and find the #tree entry and change the `overflow-x` property there.

**Comment by myksto71** [comment] 2021-12-04 08:27
glusby, I really appreciate you help, you really solved my problem. I edited the value you indicated me and also i edited the value "max-width" increasing the dafault value: now I have a folder tree that can expand as needed and all folders are visible.

I really, really thank you so much!

Cheers,
Michele.

**Closed** 2021-12-17 15:33 UTC
