### ISSUE TITLE
Zip files crashes new connection for everyone 

### ISSUE THREAD

**Issue by Infiziert90** [lrsjng/h5ai#613] opened 2017-03-17 10:11 UTC
Hi ...

i have a little problem with h5ai atm ...
when someone is using the zip file function for downloading more files, everyone else cant get an new connection. 
But i can build a connection to a other homepage that runs over the same nginx, so its failes directly in h5ai.

Friend downloading some Files per zip function:
```
PID USER PRI NI VIRT RES SHR S CPU% MEM% TIME+ Command
29274 http 20 0 10092 2332 1824 S 2.7 0.0 1:35.56 zip - -- [Filenames]
```

For me and others:
```
Error 504 Gateway time-out
```

Server System:
Proxmox [Manjaro-VM]
16GB Ram
6 Cores [Xeon E3-1245 v3]
Nginx with php7

**Comment by 23doors** [comment] 2017-03-21 12:28
it's a duplicate of https://github.com/lrsjng/h5ai/issues/326 but sadly seems to have been ignored for past few years.

**Closed** 2019-04-16 17:04 UTC
Labels: Duplicate
