### ISSUE TITLE
[Suggestion] theming/skinning

### ISSUE THREAD

**Issue by typhoon71** [lrsjng/h5ai#410] opened 2015-03-21 13:30 UTC
Can the theme as a whole be changed?
I see it's possible to customize the icons, but would it be possible to customize the rest too?
Like making it darker, changing the over color, ...
Possibly without altering the core of h5ai, like an include of sorts?

**Comment by lrsjng** [comment] 2015-03-22 12:39
This is a duplicate of #353.

**Closed by lrsjng** 2015-03-22 12:39 UTC
