### ISSUE TITLE
PHP errors.

### ISSUE THREAD

**Issue by DarkKV** [lrsjng/h5ai#416] opened 2015-04-04 18:42 UTC
Nothing major, just some php errors with the latest compiled build.

Thanks.

PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 148
PHP message: PHP Notice:  Undefined index: foldersize in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-util.php on line 162
PHP message: PHP Notice:  Undefined index: view in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 148
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 148
PHP message: PHP Notice:  Undefined index: view in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Notice:  Undefined index: view in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Notice:  Undefined index: view in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Notice:  Undefined index: view in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/webserver/**********/public_html/_h5ai/server/php/inc/class-app.php on line 106

**Comment by lrsjng** [comment] 2015-04-04 19:06
@DarkKV latest release or dev build? did you update completely? most likely can't reuse old `options.json` files..

**Comment by DarkKV** [comment] 2015-04-04 19:45
@lrsjng dev build built from source yesterday, clean install on all files.

**Comment by lrsjng** [comment] 2015-04-04 19:59
can't reproduce that, no errors on my end..

if you have a look at [line 148](https://github.com/lrsjng/h5ai/blob/master/src/_h5ai/server/php/inc/class-app.php#L148) in `class-app.php` you will notice that there is no reference to `foldersize` as mentioned in your errors..

I think something got mixed up in the install process..?

**Comment by DarkKV** [comment] 2015-04-04 20:10
@lrsjng 
Strange, maybe it was a one time thing however 
PHP Warning: Invalid argument supplied for foreach() in /home/webserver/****/public_html/_h5ai/server/php/inc/class-app.php on line 106

is recurring and the line contains the argument. This is with peer5 enabled incase that matters.

**Comment by lrsjng** [comment] 2015-04-04 20:30
do you have a live link, or can you post your `options.json`?

**Comment by DarkKV** [comment] 2015-04-04 20:34
@lrsjng  Options - http://pastebin.com/HmAbPcJV

I can email you a live link if you want.

**Comment by lrsjng** [comment] 2015-04-04 20:39
@DarkKV these error messages doesn't make sense in this context.. options look fine. are these error messages for the current install, or maybe some old logs?

**Comment by lrsjng** [comment] 2015-04-04 20:40
@DarkKV with this error messages h5ai should not be working as expected.. does everything work fine, everything green on the info page (your-domain.com/_h5ai)?

**Comment by DarkKV** [comment] 2015-04-04 20:53
@lrsjng yup, timestamp on these issue is of today. Info page reports no problems.

We've actually been having a lot of problems with peer5, it freezing on file verification and crashing peoples browsers on phone. Although I assume this issue isn't related to those of peer5.

**Comment by lrsjng** [comment] 2015-04-04 23:34
so I close this then (ref: #417)

**Closed by lrsjng** 2015-04-04 23:34 UTC
Labels: Help / Question
